site_name: Navio2 docs
theme_dir: docstheme/material
site_favicon: favicon.ico
repo_url: https://github.com/emlid/navio2-docs

extra:
  palette:
    primary: 'light blue'
    accent: 'light blue'
  logo: 'img/logo.png'
  social:
    - type: 'github'
      link: 'https://github.com/emlid'
    - type: 'twitter'
      link: 'https://twitter.com/emlidtech'
    - type: 'facebook'
      link: 'https://facebook.com/emlidtech'
  google_analytics:
    - 'UA-49508097-6'
    - 'auto'

markdown_extensions:
 - markdown.extensions.admonition
 - markdown.extensions.codehilite(guess_lang=false)
 - markdown.extensions.def_list
 - markdown.extensions.footnotes
 - markdown.extensions.meta
 - markdown.extensions.toc(permalink=true)

pages:
- 介绍 : 'index.md'
- 硬件设置: 'ardupilot/hardware-setup.md'
- Raspberry Pi配置: 'common/ardupilot/configuring-raspberry-pi.md'
- ArduPilot:
  - '典型配置': 'ardupilot/typical-setup-schemes.md'
  - '安装运行' : 'common/ardupilot/installation-and-running.md'
  - '配置' : 'ardupilot/tips.md'
  - '升级' : 'common/ardupilot/upgrade.md'
  - '从源码构建': 'common/ardupilot/building-from-sources.md'
- ROS : 'common/dev/ros.md'
- Navio2开发文档:
  - '引脚定义': 'dev/pinout.md'
  - '视频流': 'common/dev/video-streaming.md'
  - 'Wi-Fi广播' : 'common/dev/wbc.md'
  - '配置示例': 'common/dev/navio-repository-cloning.md'
  - '气压计' : 'common/dev/barometer.md'
  - 'ADC' : 'dev/adc.md'
  - 'PWM输出' : 'dev/pwm-output.md'
  - 'RC输入' : 'dev/rc-input.md'
  - 'RCIO' : 'dev/rcio.md'
  - '9DOF IMU' : 'common/dev/imu-mpu9250_lsm9ds1.md'
  - 'AHRS' : 'common/dev/ahrs.md'
  - 'GPS' : 'common/dev/gps-ublox.md'
  - 'u-center用法' : 'common/dev/gps-ublox-ucenter.md'
  - 'RGB LED' : 'common/dev/rgb-led.md'
- 变更日志: 'common/dev/changelogs.md'
- 社区项目:
  - 'Windows IoT': 'common/community-projects/Windows-IoT.md'
